Home section dipercayaoleh
creasico/creasico.github.io pull request #13
Opened 2023-07-05 09:13 UTC by alvinathoriqoh

- [ ] Bagian ini judulnya diganti Client & Partner(en dan Klien & Mitra(in). 

Kemudian memasukkan beberapa client dan partner kita, diantaranya:
- [ ] Infimedia
- [ ] Telkom Indonesia
- [ ] STN Ready Mix
- [ ] Ponpes Al Fusha

2023-07-11 06:28 UTC, feryardiant requested changes

2023-07-11 06:28 UTC, feryardiant commented on src/assets/partners.json
Untuk list lain selain ke-4 client itu, bisa dihapus aja.

2023-07-22 02:09 UTC, alvinathoriqoh commented
Menampilkan hanya 4 klient & mitra
<img width="860" alt="image" src="https://github.com/creasico/creasico.github.io/assets/117893652/e6162cf3-7c44-4e31-a0e9-6c8d96358300">

2023-07-22 02:23 UTC, feryardiant approved these changes

2023-07-22 02:23 UTC, merged